#pragma once

#ifndef _MR_BUFFERS_CONFIG_H_
#define _MR_BUFFERS_CONFIG_H_

#define MR_BUFFERS_CHECK_BIND_ERRORS 0
#define MR_BUFFERS_CHECK_MAPPINGS_ERRORS 0
#define MR_BUFFERS_CHECK_CREATION_DELETION_ERRORS 0
#define MR_BUFFERS_CHECK_BUFFER_DATA_ERRORS 0

#if (MR_BUFFERS_CHECK_BIND_ERRORS == 1) || (MR_BUFFERS_CHECK_MAPPINGS_ERRORS == 1) || (MR_BUFFERS_CHECK_CREATION_DELETION_ERRORS == 1) || (MR_BUFFERS_CHECK_BUFFER_DATA_ERRORS == 1)
    #include "../Utils/Debug.hpp"
#endif

#if (MR_BUFFERS_CHECK_BIND_ERRORS == 1)
    #define MR_BUFFERS_CHECK_BIND_ERRORS_CATCH(x, errCode) CheckGLError(x, errCode)
#else
    #define MR_BUFFERS_CHECK_BIND_ERRORS_CATCH(x, errCode) x
#endif

#if (MR_BUFFERS_CHECK_MAPPINGS_ERRORS == 1)
    #define MR_BUFFERS_CHECK_MAPPINGS_ERRORS_CATCH(x, errCode) CheckGLError(x, errCode)
#else
    #define MR_BUFFERS_CHECK_MAPPINGS_ERRORS_CATCH(x, errCode) x
#endif

#if (MR_BUFFERS_CHECK_CREATION_DELETION_ERRORS == 1)
    #define MR_BUFFERS_CHECK_CREATION_DELETION_ERRORS_CATCH(x, errCode) CheckGLError(x, errCode)
#else
    #define MR_BUFFERS_CHECK_CREATION_DELETION_ERRORS_CATCH(x, errCode) x
#endif

#if (MR_BUFFERS_CHECK_BUFFER_DATA_ERRORS == 1)
    #define MR_BUFFERS_CHECK_BUFFER_DATA_ERRORS_CATCH(x, errCode) CheckGLError(x, errCode)
#else
    #define MR_BUFFERS_CHECK_BUFFER_DATA_ERRORS_CATCH(x, errCode) x
#endif

#endif // _MR_BUFFERS_CONFIG_H_
