#pragma once

#ifndef _MR_CONFIG_H_
#define _MR_CONFIG_H_

/** COMPILE TIME CONFIG **/
#define GLEW_STATIC
#define GLM_FORCE_CXX11
#define MR_USE_OPENMP

/** COMPILE TIME ENGINE CONSTANTS **/
#define MR_DELTA_TYPE float

#define MR_DEFAULT_TEXTURE_SETTINGS_LOD_BIAS 0.0f
#define MR_DEFAULT_TEXTURE_SETTINGS_BORDER_COLOR 0.0f, 0.0f, 0.0f, 0.0f
#define MR_DEFAULT_TEXTURE_SETTINGS_MAG_FILTER MagFilter::LINEAR
#define MR_DEFAULT_TEXTURE_SETTINGS_MIN_FILTER MinFilter::LINEAR
#define MR_DEFAULT_TEXTURE_SETTINGS_MIN_LOD -1000
#define MR_DEFAULT_TEXTURE_SETTINGS_MAX_LOD 1000
#define MR_DEFAULT_TEXTURE_SETTINGS_WRAP_S Wrap::CLAMP
#define MR_DEFAULT_TEXTURE_SETTINGS_WRAP_R Wrap::CLAMP
#define MR_DEFAULT_TEXTURE_SETTINGS_WRAP_T Wrap::CLAMP
#define MR_DEFAULT_TEXTURE_SETTINGS_COMPARE_MODE CompareMode::NONE
#define MR_DEFAULT_TEXTURE_SETTINGS_COMPARE_FUNC CompareFunc::LEQUAL
#define MR_TEXTURE_DIFFUSE_STAGE GL_TEXTURE0

#define MR_SHADER_VERTEX_POSITION_ATTRIB_LOCATION 0
#define MR_SHADER_VERTEX_NORMAL_ATTRIB_LOCATION 1
#define MR_SHADER_VERTEX_COLOR_ATTRIB_LOCATION 2
#define MR_SHADER_VERTEX_TEXCOORD_ATTRIB_LOCATION 3

#endif // _MR_CONFIG_H_
