#pragma once

#include "pre/glm.hpp"

#include "core.hpp"
#include "log.hpp"
#include "info.hpp"
#include "buffer.hpp"
#include "vformat.hpp"
#include "vbuffer.hpp"
#include "ibuffer.hpp"
#include "draw.hpp"
#include "shader/shader.hpp"
#include "shader/program.hpp"
#include "timer.hpp"
#include "json.hpp"
#include "texture.hpp"
#include "material/MaterialShader.hpp"
#include "camera.hpp"
#include "string.hpp"
#include "shader/ubo.hpp"
