#pragma once

#ifndef _MR_MATERIALS_CONFIG_H_
#define _MR_MATERIALS_CONFIG_H_

#define MR_MATERIAL_EMISSION_TEX_DEFAULT 1
#define MR_MATERIAL_ALBEDO_TEX_DEFAULT 2
#define MR_MATERIAL_OPACITYMASK_TEX_DEFAULT 3
#define MR_MATERIAL_ALPHA_DISCARD_F_DEFAULT 0.5f
#define MR_MATERIAL_COLOR_V4_DEFAULT        1,1,1,1
#define MR_MATERIAL_EMISSIVE_V4_DEFAULT     0,0,0,0

#endif // _MR_MATERIALS_CONFIG_H_
